// <auto-generated />
namespace AnunciosWebAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PrecoVendido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrecoVendido));
        
        string IMigrationMetadata.Id
        {
            get { return "201303161916181_PrecoVendido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
